BASE_URL = "https://qa-scooter.praktikum-services.ru"
CREATE_COURIER_ENDPOINT = "/api/v1/courier"
LOGIN_COURIER_ENDPOINT = "/api/v1/courier/login"
DELETE_COURIER_ENDPOINT = "/api/v1/courier/{}"
ORDERS_ENDPOINT = "/api/v1/orders"
